/**
 * Generates src/components/controlsbar.css — Memphis controls bar.
 *
 * This component is Memphis-only (no SilicaUI equivalent).
 * Flex column on mobile, row on desktop, with container border.
 */

import { writeFile } from 'fs/promises';

export async function generateControlsbarCss() {
    const css = `/* Generated by scripts/generate.ts — do not edit manually */

.controls-bar {
  @layer memphis.component {
    display: flex;
    flex-direction: column;
    align-items: stretch;
    gap: 1rem;
    padding: 1rem;
    background-color: var(--color-base-100);
    border: var(--border-container) solid var(--color-dark);
    border-radius: 0;

    @media (min-width: 768px) {
      flex-direction: row;
      align-items: center;
    }
  }
}
`;

    await writeFile('src/components/controlsbar.css', css);
    console.log('  ✓ src/components/controlsbar.css');
}
