/**
 * Generates src/themes/memphis.css — All Memphis CSS variable declarations.
 *
 * Outputs a complete set of color variables for every palette color:
 * --color-{name}, --color-{name}-hover, --color-{name}-light,
 * --color-{name}-focus, --color-{name}-content
 */

import { writeFile, mkdir } from 'fs/promises';
import { config } from '../../src/theme.config.js';

export async function generateThemeCss() {
    const lines: string[] = ['/* Generated by scripts/generate.ts — do not edit manually */'];
    lines.push('color-scheme: light;');
    lines.push('');

    // ── Core Memphis Palette ────────────────────────────────────────
    lines.push('/* ═══ Core Memphis Palette ═══ */');
    const coreColors = ['coral', 'teal', 'yellow', 'purple', 'dark', 'cream'];
    for (const name of coreColors) {
        const def = config.colors[name];
        if (!def) continue;
        lines.push(`--color-${name}: ${def.hex};`);
        lines.push(`--color-${name}-hover: ${def.hover};`);
        lines.push(`--color-${name}-light: ${def.light};`);
        lines.push(`--color-${name}-focus: ${def.focus};`);
        lines.push(`--color-${name}-content: ${def.content};`);
    }
    lines.push('');

    // ── Extended Palette ────────────────────────────────────────────
    lines.push('/* ═══ Extended Palette ═══ */');
    for (const [name, def] of Object.entries(config.colors)) {
        if (coreColors.includes(name)) continue; // already output above
        lines.push(`--color-${name}: ${def.hex};`);
        lines.push(`--color-${name}-hover: ${def.hover};`);
        lines.push(`--color-${name}-light: ${def.light};`);
        lines.push(`--color-${name}-focus: ${def.focus};`);
        lines.push(`--color-${name}-content: ${def.content};`);
    }
    lines.push('');

    // ── Fixed Base Colors ───────────────────────────────────────────
    lines.push('/* ═══ Base Colors ═══ */');
    lines.push(`--color-white: #FFFFFF;`);
    lines.push(`--color-black: #000000;`);
    lines.push(`--color-dark-gray: ${config.darkGray};`);
    lines.push(`--color-dark-overlay: ${config.darkOverlay};`);
    lines.push('');

    // ── Semantic Colors (DaisyUI compat) ────────────────────────────
    lines.push('/* ═══ Semantic Colors ═══ */');
    for (const [semantic, colorName] of Object.entries(config.semantic)) {
        const def = config.colors[colorName];
        lines.push(`--color-${semantic}: ${def.hex};`);
        lines.push(`--color-${semantic}-content: ${def.content};`);
    }
    lines.push('');

    // ── Base Scale ──────────────────────────────────────────────────
    lines.push('/* ═══ Base Scale ═══ */');
    lines.push(`--color-base-100: ${config.base[100]};`);
    lines.push(`--color-base-200: ${config.base[200]};`);
    lines.push(`--color-base-300: ${config.base[300]};`);
    lines.push(`--color-base-content: ${config.base.content};`);
    lines.push('');

    // ── Geometry (Memphis: sharp corners) ───────────────────────────
    lines.push('/* ═══ Geometry ═══ */');
    lines.push('--radius-selector: 0;');
    lines.push('--radius-field: 0;');
    lines.push('--radius-box: 0;');
    lines.push('--size-selector: 0.25rem;');
    lines.push('--size-field: 0.25rem;');
    lines.push(`--border: ${config.borders.container};`);
    lines.push('--depth: 0;');
    lines.push('--noise: 0;');
    lines.push('');

    // ── Border Tiers ────────────────────────────────────────────────
    lines.push('/* ═══ Border Tiers ═══ */');
    for (const [name, value] of Object.entries(config.borders)) {
        lines.push(`--border-${name}: ${value};`);
    }
    lines.push('');

    // ── Design Tokens ───────────────────────────────────────────────
    lines.push('/* ═══ Design Tokens ═══ */');
    for (const [name, value] of Object.entries(config.tokens)) {
        lines.push(`--${name}: ${value};`);
    }
    lines.push('');

    // ── Legacy Geometry (DaisyUI compat) ────────────────────────────
    lines.push('/* ═══ Legacy Geometry ═══ */');
    for (const [name, value] of Object.entries(config.geometry)) {
        lines.push(`--${name}: ${value};`);
    }
    lines.push('');

    // ── Accent Cycle ────────────────────────────────────────────────
    lines.push(`--accent-cycle: [${config.accentCycle.join(', ')}];`);

    await mkdir('src/themes', { recursive: true });
    await writeFile('src/themes/memphis.css', lines.join('\n') + '\n');
    console.log('  ✓ src/themes/memphis.css');
}
