/**
 * Generates src/utilities/memphis.css — Memphis-specific utility classes.
 *
 * Border tier utilities, bg-*-light backgrounds, text-*-content utilities.
 */

import { writeFile } from 'fs/promises';
import { config } from '../../src/theme.config.js';

export async function generateUtilitiesCss() {
    const lines: string[] = ['/* Generated by scripts/generate.ts — do not edit manually */'];
    lines.push('');

    // Border tier utilities
    lines.push('/* Border tier utilities */');
    for (const [tier] of Object.entries(config.borders)) {
        lines.push(`.border-${tier} {`);
        lines.push(`  border: var(--border-${tier}) solid var(--color-dark);`);
        lines.push('}');
    }
    lines.push('');

    // bg-{color}-light utilities
    lines.push('/* Light background utilities */');
    for (const [name] of Object.entries(config.colors)) {
        lines.push(`.bg-${name}-light {`);
        lines.push(`  background-color: var(--color-${name}-light);`);
        lines.push('}');
    }
    lines.push('');

    // bg-{color}-focus utilities
    lines.push('/* Focus background utilities */');
    for (const [name] of Object.entries(config.colors)) {
        lines.push(`.bg-${name}-focus {`);
        lines.push(`  background-color: var(--color-${name}-focus);`);
        lines.push('}');
    }
    lines.push('');

    // text-{color}-content utilities
    lines.push('/* Content text utilities */');
    for (const [name] of Object.entries(config.colors)) {
        lines.push(`.text-${name}-content {`);
        lines.push(`  color: var(--color-${name}-content);`);
        lines.push('}');
    }

    await writeFile('src/utilities/memphis.css', lines.join('\n') + '\n');
    console.log('  ✓ src/utilities/memphis.css');
}
