/**
 * Generates functions/variables.js — theme.extend.colors mapping for Tailwind.
 * This enables @apply border-coral, bg-teal, text-primary, etc.
 *
 * Now outputs all color variants: base, hover, light, focus, content.
 */

import { writeFile } from 'fs/promises';
import { config } from '../../src/theme.config.js';

export async function generateVariablesJs() {
    const colors: Record<string, string> = {};

    // All palette colors with full variant set
    for (const [name] of Object.entries(config.colors)) {
        colors[name] = `var(--color-${name})`;
        colors[`${name}-hover`] = `var(--color-${name}-hover)`;
        colors[`${name}-light`] = `var(--color-${name}-light)`;
        colors[`${name}-focus`] = `var(--color-${name}-focus)`;
        colors[`${name}-content`] = `var(--color-${name}-content)`;
    }

    // Fixed base colors
    colors['white'] = 'var(--color-white)';
    colors['black'] = 'var(--color-black)';
    colors['dark-gray'] = 'var(--color-dark-gray)';
    colors['dark-overlay'] = 'var(--color-dark-overlay)';

    // Semantic colors
    for (const semantic of Object.keys(config.semantic)) {
        colors[semantic] = `var(--color-${semantic})`;
        colors[`${semantic}-content`] = `var(--color-${semantic}-content)`;
    }

    // Base scale
    colors['base-100'] = 'var(--color-base-100)';
    colors['base-200'] = 'var(--color-base-200)';
    colors['base-300'] = 'var(--color-base-300)';
    colors['base-content'] = 'var(--color-base-content)';

    const entries = Object.entries(colors)
        .map(([k, v]) => `        "${k}": "${v}"`)
        .join(',\n');

    const content = `/** Generated by scripts/generate.ts — do not edit manually */

export default {
    colors: {
${entries}
    },
    borderRadius: {
        selector: "var(--radius-selector)",
        field: "var(--radius-field)",
        box: "var(--radius-box)",
    },
    borderWidth: {
        container: "var(--border-container)",
        interactive: "var(--border-interactive)",
        detail: "var(--border-detail)",
    },
}
`;

    await writeFile('functions/variables.js', content);
    console.log('  ✓ functions/variables.js');
}
