/**
 * Matches V3 Routes — GET list, GET by id, PATCH (no POST/DELETE)
 * Matches are generated by the orchestrator, not manually created
 */

import { FastifyInstance } from 'fastify';
import { SupabaseClient } from '@supabase/supabase-js';
import { IEventPublisher } from '../../v2/shared/events.js';
import { MatchRepository } from './repository.js';
import { MatchService } from './service.js';
import { registerEnrichedMatchView } from './views/enriched.route.js';
import { registerInviteAction } from './actions/invite.route.js';
import { registerDismissAction } from './actions/dismiss.route.js';
import { registerDenyInviteAction } from './actions/deny-invite.route.js';
import {
  UpdateMatchInput, MatchListParams,
  idParamSchema, listQuerySchema, updateMatchSchema,
} from './types.js';

export function registerMatchRoutes(
  app: FastifyInstance,
  supabase: SupabaseClient,
  eventPublisher?: IEventPublisher,
) {
  // Register views and actions before CRUD to avoid param collision
  registerEnrichedMatchView(app, supabase);
  registerInviteAction(app, supabase, eventPublisher);
  registerDismissAction(app, supabase, eventPublisher);
  registerDenyInviteAction(app, supabase, eventPublisher);

  const repository = new MatchRepository(supabase);
  const service = new MatchService(repository, supabase, eventPublisher);

  // GET /api/v3/matches
  app.get('/api/v3/matches', {
    schema: { querystring: listQuerySchema },
  }, async (request, reply) => {
    const clerkUserId = request.headers['x-clerk-user-id'] as string;
    if (!clerkUserId) {
      return reply.status(401).send({ error: { code: 'AUTH_REQUIRED', message: 'Authentication required' } });
    }
    const result = await service.getAll(request.query as MatchListParams, clerkUserId);
    return reply.send({ data: result.data, pagination: result.pagination });
  });

  // GET /api/v3/matches/:id
  app.get('/api/v3/matches/:id', {
    schema: { params: idParamSchema },
  }, async (request, reply) => {
    const clerkUserId = request.headers['x-clerk-user-id'] as string;
    if (!clerkUserId) {
      return reply.status(401).send({ error: { code: 'AUTH_REQUIRED', message: 'Authentication required' } });
    }
    const { id } = request.params as { id: string };
    const data = await service.getById(id, clerkUserId);
    return reply.send({ data });
  });

  // PATCH /api/v3/matches/:id
  app.patch('/api/v3/matches/:id', {
    schema: { params: idParamSchema, body: updateMatchSchema },
  }, async (request, reply) => {
    const clerkUserId = request.headers['x-clerk-user-id'] as string;
    if (!clerkUserId) {
      return reply.status(401).send({ error: { code: 'AUTH_REQUIRED', message: 'Authentication required' } });
    }
    const { id } = request.params as { id: string };
    const data = await service.update(id, request.body as UpdateMatchInput, clerkUserId);
    return reply.send({ data });
  });
}
