apiVersion: v1
kind: Service
metadata:
    name: livekit-server-lb
    namespace: splits-network
    annotations:
        service.beta.kubernetes.io/azure-pip-name: livekit-public-ip
        service.beta.kubernetes.io/azure-load-balancer-resource-group: ${LIVEKIT_LB_RESOURCE_GROUP}
spec:
    type: LoadBalancer
    loadBalancerIP: ${LIVEKIT_EXTERNAL_IP}
    ports:
        - name: rtc-tcp
          port: 7881
          targetPort: 7881
          protocol: TCP
        - name: turn-udp
          port: 3478
          targetPort: 3478
          protocol: UDP
    selector:
        app: livekit-server
