export const data = {
    firmName: "Apex Talent Partners",
    status: "active",
    isNew: true,
    isOnline: true,
    name: "Sarah Mitchell",
    initials: "SM",
    tagline: "Enterprise SaaS Specialist",
    location: "San Francisco, CA",
    memberSince: "Jan 2024",
    stats: [
        { label: "Placed", value: "47", icon: "fa-duotone fa-regular fa-handshake" },
        { label: "Success", value: "72%", icon: "fa-duotone fa-regular fa-bullseye" },
        { label: "Rating", value: "4.9", icon: "fa-duotone fa-regular fa-star" },
        { label: "Exp.", value: "8 yr", icon: "fa-duotone fa-regular fa-clock" },
    ],
    bio: "Experienced technical recruiter specializing in enterprise SaaS placements. I partner with high-growth startups and Fortune 500 companies to build world-class engineering teams.",
    specialties: ["Full-Stack", "DevOps", "Machine Learning", "Product Management"],
    industries: ["SaaS", "FinTech", "HealthTech", "AI/ML"],
    isCompanyRecruiter: true,
    isCandidateRecruiter: true,
    email: "sarah.mitchell@apextalent.com",
    phone: "+1 (415) 555-0192",
};
