-- ============================================================
-- Seed ~500 curated skills across tech & business categories
-- Slugs are pre-computed: lowercase, non-alphanumeric stripped (except + and #)
-- ============================================================

INSERT INTO skills (name, slug) VALUES
-- Programming Languages
('JavaScript', 'javascript'),
('TypeScript', 'typescript'),
('Python', 'python'),
('Java', 'java'),
('C#', 'c#'),
('C++', 'c++'),
('C', 'c'),
('Go', 'go'),
('Rust', 'rust'),
('Ruby', 'ruby'),
('PHP', 'php'),
('Swift', 'swift'),
('Kotlin', 'kotlin'),
('Scala', 'scala'),
('R', 'r'),
('MATLAB', 'matlab'),
('Perl', 'perl'),
('Haskell', 'haskell'),
('Elixir', 'elixir'),
('Erlang', 'erlang'),
('Clojure', 'clojure'),
('Dart', 'dart'),
('Lua', 'lua'),
('Julia', 'julia'),
('Objective-C', 'objectivec'),
('Assembly', 'assembly'),
('COBOL', 'cobol'),
('Fortran', 'fortran'),
('Groovy', 'groovy'),
('F#', 'f#'),
('Visual Basic', 'visualbasic'),
('Shell Scripting', 'shellscripting'),
('Bash', 'bash'),
('PowerShell', 'powershell'),
('SQL', 'sql'),
('PL/pgSQL', 'plpgsql'),
('GraphQL', 'graphql'),
('Solidity', 'solidity'),
('Zig', 'zig'),

-- Frontend Frameworks & Libraries
('React', 'react'),
('Next.js', 'nextjs'),
('Vue.js', 'vuejs'),
('Angular', 'angular'),
('Svelte', 'svelte'),
('SvelteKit', 'sveltekit'),
('Nuxt.js', 'nuxtjs'),
('Remix', 'remix'),
('Astro', 'astro'),
('Solid.js', 'solidjs'),
('jQuery', 'jquery'),
('Ember.js', 'emberjs'),
('Backbone.js', 'backbonejs'),
('Alpine.js', 'alpinejs'),
('htmx', 'htmx'),
('Preact', 'preact'),
('Gatsby', 'gatsby'),
('Qwik', 'qwik'),

-- CSS & Styling
('CSS', 'css'),
('Tailwind CSS', 'tailwindcss'),
('Sass', 'sass'),
('Less', 'less'),
('Bootstrap', 'bootstrap'),
('Material UI', 'materialui'),
('Chakra UI', 'chakraui'),
('Styled Components', 'styledcomponents'),
('CSS Modules', 'cssmodules'),
('PostCSS', 'postcss'),
('DaisyUI', 'daisyui'),
('Ant Design', 'antdesign'),
('Radix UI', 'radixui'),
('Shadcn UI', 'shadcnui'),

-- Backend Frameworks
('Node.js', 'nodejs'),
('Express.js', 'expressjs'),
('Fastify', 'fastify'),
('NestJS', 'nestjs'),
('Django', 'django'),
('Flask', 'flask'),
('FastAPI', 'fastapi'),
('Spring Boot', 'springboot'),
('Spring', 'spring'),
('Ruby on Rails', 'rubyonrails'),
('Laravel', 'laravel'),
('ASP.NET', 'aspnet'),
('ASP.NET Core', 'aspnetcore'),
('Gin', 'gin'),
('Echo', 'echo'),
('Fiber', 'fiber'),
('Phoenix', 'phoenix'),
('Actix', 'actix'),
('Koa', 'koa'),
('Hono', 'hono'),
('Deno', 'deno'),
('Bun', 'bun'),

-- Databases
('PostgreSQL', 'postgresql'),
('MySQL', 'mysql'),
('MongoDB', 'mongodb'),
('Redis', 'redis'),
('SQLite', 'sqlite'),
('Microsoft SQL Server', 'microsoftsqlserver'),
('Oracle Database', 'oracledatabase'),
('Cassandra', 'cassandra'),
('DynamoDB', 'dynamodb'),
('CouchDB', 'couchdb'),
('Neo4j', 'neo4j'),
('Elasticsearch', 'elasticsearch'),
('InfluxDB', 'influxdb'),
('MariaDB', 'mariadb'),
('Supabase', 'supabase'),
('Firebase', 'firebase'),
('PlanetScale', 'planetscale'),
('Neon', 'neon'),
('CockroachDB', 'cockroachdb'),
('TimescaleDB', 'timescaledb'),
('ClickHouse', 'clickhouse'),
('Drizzle ORM', 'drizzleorm'),
('Prisma', 'prisma'),
('TypeORM', 'typeorm'),
('Sequelize', 'sequelize'),
('Knex.js', 'knexjs'),
('Mongoose', 'mongoose'),
('SQLAlchemy', 'sqlalchemy'),

-- Cloud Platforms
('AWS', 'aws'),
('Microsoft Azure', 'microsoftazure'),
('Google Cloud Platform', 'googlecloudplatform'),
('Heroku', 'heroku'),
('Vercel', 'vercel'),
('Netlify', 'netlify'),
('DigitalOcean', 'digitalocean'),
('Cloudflare', 'cloudflare'),
('Fly.io', 'flyio'),
('Railway', 'railway'),
('Render', 'render'),

-- AWS Services
('AWS Lambda', 'awslambda'),
('AWS S3', 'awss3'),
('AWS EC2', 'awsec2'),
('AWS ECS', 'awsecs'),
('AWS EKS', 'awseks'),
('AWS RDS', 'awsrds'),
('AWS CloudFormation', 'awscloudformation'),
('AWS SQS', 'awssqs'),
('AWS SNS', 'awssns'),
('AWS API Gateway', 'awsapigateway'),
('AWS CDK', 'awscdk'),
('AWS DynamoDB', 'awsdynamodb'),
('AWS Cognito', 'awscognito'),

-- DevOps & Infrastructure
('Docker', 'docker'),
('Kubernetes', 'kubernetes'),
('Terraform', 'terraform'),
('Ansible', 'ansible'),
('Pulumi', 'pulumi'),
('Helm', 'helm'),
('Jenkins', 'jenkins'),
('GitHub Actions', 'githubactions'),
('GitLab CI/CD', 'gitlabcicd'),
('CircleCI', 'circleci'),
('Travis CI', 'travisci'),
('ArgoCD', 'argocd'),
('Nginx', 'nginx'),
('Apache', 'apache'),
('Caddy', 'caddy'),
('Linux', 'linux'),
('Ubuntu', 'ubuntu'),
('CentOS', 'centos'),
('Prometheus', 'prometheus'),
('Grafana', 'grafana'),
('Datadog', 'datadog'),
('New Relic', 'newrelic'),
('PagerDuty', 'pagerduty'),
('Splunk', 'splunk'),
('ELK Stack', 'elkstack'),
('Vagrant', 'vagrant'),
('Istio', 'istio'),
('Consul', 'consul'),

-- Version Control
('Git', 'git'),
('GitHub', 'github'),
('GitLab', 'gitlab'),
('Bitbucket', 'bitbucket'),
('SVN', 'svn'),

-- Testing
('Jest', 'jest'),
('Vitest', 'vitest'),
('Mocha', 'mocha'),
('Cypress', 'cypress'),
('Playwright', 'playwright'),
('Selenium', 'selenium'),
('Testing Library', 'testinglibrary'),
('Puppeteer', 'puppeteer'),
('JUnit', 'junit'),
('PyTest', 'pytest'),
('RSpec', 'rspec'),
('Storybook', 'storybook'),
('Enzyme', 'enzyme'),
('Jasmine', 'jasmine'),
('Karma', 'karma'),
('Detox', 'detox'),
('Appium', 'appium'),

-- Mobile Development
('React Native', 'reactnative'),
('Flutter', 'flutter'),
('iOS Development', 'iosdevelopment'),
('Android Development', 'androiddevelopment'),
('SwiftUI', 'swiftui'),
('Jetpack Compose', 'jetpackcompose'),
('Expo', 'expo'),
('Xamarin', 'xamarin'),
('Ionic', 'ionic'),
('Capacitor', 'capacitor'),
('Cordova', 'cordova'),

-- AI & Machine Learning
('Machine Learning', 'machinelearning'),
('Deep Learning', 'deeplearning'),
('Natural Language Processing', 'naturallanguageprocessing'),
('Computer Vision', 'computervision'),
('TensorFlow', 'tensorflow'),
('PyTorch', 'pytorch'),
('Scikit-learn', 'scikitlearn'),
('Keras', 'keras'),
('OpenCV', 'opencv'),
('Hugging Face', 'huggingface'),
('LangChain', 'langchain'),
('OpenAI API', 'openaiapi'),
('LLM Fine-Tuning', 'llmfinetuning'),
('Prompt Engineering', 'promptengineering'),
('RAG', 'rag'),
('Vector Databases', 'vectordatabases'),
('MLOps', 'mlops'),
('Data Science', 'datascience'),
('Pandas', 'pandas'),
('NumPy', 'numpy'),
('Jupyter', 'jupyter'),
('Apache Spark', 'apachespark'),
('Hadoop', 'hadoop'),

-- Data Engineering
('ETL', 'etl'),
('Apache Kafka', 'apachekafka'),
('RabbitMQ', 'rabbitmq'),
('Apache Airflow', 'apacheairflow'),
('dbt', 'dbt'),
('Snowflake', 'snowflake'),
('BigQuery', 'bigquery'),
('Redshift', 'redshift'),
('Data Warehousing', 'datawarehousing'),
('Data Modeling', 'datamodeling'),
('Apache Flink', 'apacheflink'),
('Databricks', 'databricks'),

-- Security
('Cybersecurity', 'cybersecurity'),
('Penetration Testing', 'penetrationtesting'),
('OAuth', 'oauth'),
('JWT', 'jwt'),
('OWASP', 'owasp'),
('SSL/TLS', 'ssltls'),
('SOC 2', 'soc2'),
('GDPR', 'gdpr'),
('HIPAA', 'hipaa'),
('Identity Management', 'identitymanagement'),
('Zero Trust', 'zerotrust'),
('SIEM', 'siem'),

-- API & Integration
('REST API', 'restapi'),
('gRPC', 'grpc'),
('WebSockets', 'websockets'),
('SOAP', 'soap'),
('Webhooks', 'webhooks'),
('API Design', 'apidesign'),
('Swagger', 'swagger'),
('OpenAPI', 'openapi'),
('Postman', 'postman'),
('Insomnia', 'insomnia'),
('tRPC', 'trpc'),

-- Design & UX
('Figma', 'figma'),
('Adobe XD', 'adobexd'),
('Sketch', 'sketch'),
('UI Design', 'uidesign'),
('UX Design', 'uxdesign'),
('User Research', 'userresearch'),
('Wireframing', 'wireframing'),
('Prototyping', 'prototyping'),
('Design Systems', 'designsystems'),
('Responsive Design', 'responsivedesign'),
('Accessibility', 'accessibility'),
('Adobe Photoshop', 'adobephotoshop'),
('Adobe Illustrator', 'adobeillustrator'),
('InVision', 'invision'),
('Zeplin', 'zeplin'),
('Framer', 'framer'),
('Canva', 'canva'),

-- Project Management & Collaboration
('Agile', 'agile'),
('Scrum', 'scrum'),
('Kanban', 'kanban'),
('Jira', 'jira'),
('Confluence', 'confluence'),
('Trello', 'trello'),
('Asana', 'asana'),
('Linear', 'linear'),
('Notion', 'notion'),
('Monday.com', 'mondaycom'),
('ClickUp', 'clickup'),
('Slack', 'slack'),
('Microsoft Teams', 'microsoftteams'),

-- Architecture & Patterns
('Microservices', 'microservices'),
('Monolith', 'monolith'),
('Serverless', 'serverless'),
('Event-Driven Architecture', 'eventdrivenarchitecture'),
('Domain-Driven Design', 'domaindrivendesign'),
('CQRS', 'cqrs'),
('Clean Architecture', 'cleanarchitecture'),
('MVC', 'mvc'),
('MVVM', 'mvvm'),
('SOA', 'soa'),
('System Design', 'systemdesign'),
('API Architecture', 'apiarchitecture'),
('Distributed Systems', 'distributedsystems'),

-- Build Tools & Package Managers
('Webpack', 'webpack'),
('Vite', 'vite'),
('Rollup', 'rollup'),
('esbuild', 'esbuild'),
('Turbopack', 'turbopack'),
('npm', 'npm'),
('Yarn', 'yarn'),
('pnpm', 'pnpm'),
('Gradle', 'gradle'),
('Maven', 'maven'),
('Make', 'make'),
('CMake', 'cmake'),
('Turborepo', 'turborepo'),
('Nx', 'nx'),
('Lerna', 'lerna'),
('Bazel', 'bazel'),

-- CMS & E-Commerce
('WordPress', 'wordpress'),
('Shopify', 'shopify'),
('Contentful', 'contentful'),
('Strapi', 'strapi'),
('Sanity', 'sanity'),
('Drupal', 'drupal'),
('Magento', 'magento'),
('WooCommerce', 'woocommerce'),
('Headless CMS', 'headlesscms'),
('Ghost', 'ghost'),

-- Game Development
('Unity', 'unity'),
('Unreal Engine', 'unrealengine'),
('Godot', 'godot'),
('Game Design', 'gamedesign'),
('3D Modeling', '3dmodeling'),
('WebGL', 'webgl'),
('Three.js', 'threejs'),

-- Blockchain & Web3
('Blockchain', 'blockchain'),
('Ethereum', 'ethereum'),
('Smart Contracts', 'smartcontracts'),
('Web3', 'web3'),
('DeFi', 'defi'),
('NFT', 'nft'),
('Hardhat', 'hardhat'),
('Foundry', 'foundry'),

-- Business & Soft Skills
('Technical Leadership', 'technicalleadership'),
('Team Management', 'teammanagement'),
('Mentoring', 'mentoring'),
('Code Review', 'codereview'),
('Technical Writing', 'technicalwriting'),
('Public Speaking', 'publicspeaking'),
('Cross-Functional Collaboration', 'crossfunctionalcollaboration'),
('Stakeholder Management', 'stakeholdermanagement'),
('Problem Solving', 'problemsolving'),
('Communication', 'communication'),
('Project Planning', 'projectplanning'),
('Risk Management', 'riskmanagement'),
('Budget Management', 'budgetmanagement'),
('Vendor Management', 'vendormanagement'),
('Strategic Thinking', 'strategicthinking'),
('Decision Making', 'decisionmaking'),
('Negotiation', 'negotiation'),

-- Analytics & Business Intelligence
('Google Analytics', 'googleanalytics'),
('Mixpanel', 'mixpanel'),
('Amplitude', 'amplitude'),
('Tableau', 'tableau'),
('Power BI', 'powerbi'),
('Looker', 'looker'),
('Metabase', 'metabase'),
('A/B Testing', 'abtesting'),
('Data Visualization', 'datavisualization'),
('Business Intelligence', 'businessintelligence'),
('Excel', 'excel'),
('Google Sheets', 'googlesheets'),

-- Marketing & Growth
('SEO', 'seo'),
('SEM', 'sem'),
('Content Marketing', 'contentmarketing'),
('Email Marketing', 'emailmarketing'),
('Social Media Marketing', 'socialmediamarketing'),
('Google Ads', 'googleads'),
('Facebook Ads', 'facebookads'),
('HubSpot', 'hubspot'),
('Salesforce', 'salesforce'),
('Marketo', 'marketo'),
('Growth Hacking', 'growthhacking'),
('Product Marketing', 'productmarketing'),
('Conversion Optimization', 'conversionoptimization'),

-- Product Management
('Product Management', 'productmanagement'),
('Product Strategy', 'productstrategy'),
('Roadmap Planning', 'roadmapplanning'),
('User Story Writing', 'userstorywriting'),
('Feature Prioritization', 'featureprioritization'),
('Product Analytics', 'productanalytics'),
('Customer Discovery', 'customerdiscovery'),
('OKRs', 'okrs'),
('KPI Management', 'kpimanagement'),

-- Finance & Accounting
('Financial Modeling', 'financialmodeling'),
('Accounting', 'accounting'),
('Budgeting', 'budgeting'),
('Financial Analysis', 'financialanalysis'),
('QuickBooks', 'quickbooks'),
('NetSuite', 'netsuite'),
('SAP', 'sap'),

-- HR & Recruiting
('Talent Acquisition', 'talentacquisition'),
('Recruiting', 'recruiting'),
('Sourcing', 'sourcing'),
('Employer Branding', 'employerbranding'),
('Onboarding', 'onboarding'),
('Performance Management', 'performancemanagement'),
('Compensation Planning', 'compensationplanning'),
('HRIS', 'hris'),
('ATS', 'ats'),
('Diversity & Inclusion', 'diversityinclusion'),

-- Legal & Compliance
('Contract Management', 'contractmanagement'),
('Regulatory Compliance', 'regulatorycompliance'),
('Intellectual Property', 'intellectualproperty'),
('Privacy Law', 'privacylaw'),
('Employment Law', 'employmentlaw'),

-- Miscellaneous Tech
('WebAssembly', 'webassembly'),
('Progressive Web Apps', 'progressivewebapps'),
('Service Workers', 'serviceworkers'),
('Web Performance', 'webperformance'),
('SEO Technical', 'seotechnical'),
('Internationalization', 'internationalization'),
('Localization', 'localization'),
('CI/CD', 'cicd'),
('Infrastructure as Code', 'infrastructureascode'),
('Site Reliability Engineering', 'sitereliabilityengineering'),
('Platform Engineering', 'platformengineering'),
('DevSecOps', 'devsecops'),
('Observability', 'observability'),
('Chaos Engineering', 'chaosengineering'),
('Feature Flags', 'featureflags'),
('LaunchDarkly', 'launchdarkly'),
('Stripe', 'stripe'),
('Twilio', 'twilio'),
('SendGrid', 'sendgrid'),
('Auth0', 'auth0'),
('Clerk', 'clerk'),
('Okta', 'okta'),
('SAML', 'saml'),
('SSO', 'sso'),
('Resend', 'resend')
ON CONFLICT (slug) DO NOTHING;
